name: dart_strapi
description: dart client for Strapi V4
version: 2.0.0
homepage: https://github.com/xantiagoma/dart_strapi

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: 6.7.1
  test: ^1.24.6
